### ISSUE TITLE
Tweak FAQ and downloaded files section for participant IDs to allow for future additions

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-docs#107]
There will be projects released shortly that do not currently have multiple samples that map to the same participant, but we expect future releases to include samples to meet that condition. The investigator has asked us to include participant IDs so that we don't have to make any revisions later.

As such, we're going to need to change the language in this FAQ to cover these cases: https://github.com/AlexsLemonade/scpca-docs/blob/5c66caa36f99b764f9f770e282b5787e318f3029/docs/faq.md#why-do-some-samples-have-missing-participant-ids

**Edit:** Also need to address this section: https://github.com/AlexsLemonade/scpca-docs/blob/5c66caa36f99b764f9f770e282b5787e318f3029/docs/download_files.md#metadata, so I've updated the title accordingly.

Anyone who implements this should find all "participant" to be sure everything has been addressed.

**Comment by allyhawkins** [comment]
Closed by #108
