### ISSUE TITLE
Note that bulk data is no longer required for multiplexing!

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-docs#111]
Just noting that we will also want to update the docs to note that bulk sequencing is no longer required too.

_Originally posted by @allyhawkins in https://github.com/AlexsLemonade/scpca-nf/pull/329#pullrequestreview-1444530920_

**Comment by sjspielman** [comment]
This functionality is planned to be included in the next release, so let's get those docs updated. 
Context: https://github.com/AlexsLemonade/scpca-nf/issues/353

**Comment by jashapiro** [comment]
It is actually in the current release! That PR went straight to `main`.

**Comment by sjspielman** [comment]
> It is actually in the current release! That PR went straight to `main`.

Ah well even more of a reason to do the thing!

**Comment by sjspielman** [comment]
Hm, I actually wonder if this issue should be in `scpca-nf`?

See here:
https://github.com/AlexsLemonade/scpca-nf/blob/b8daa2a2f9022dc3ead6ea17bc17ac4a06ec531c/external-instructions.md?plain=1#L329-L331

**Comment by jashapiro** [comment]
> Hm, I actually wonder if this issue should be in `scpca-nf`?
> 
> See here: https://github.com/AlexsLemonade/scpca-nf/blob/c9daa387f7e5137fe0bfde62bbe43de8d1a5ce5c/external-instructions.md?plain=1#L363-L365

That is updated and correct. We do need bulk for _genetic_ demultiplexing, but not for cellhash demultiplexing, as the next sentence states.

**Comment by sjspielman** [comment]
Looking through backlog issues, and I think this can be closed? In `processing_information.md`, bulk re-multiplexing is only mentioned for genetic, not HTO.

**Comment by jashapiro** [comment]
Looks good to me. Closing
