### ISSUE TITLE
Revamp `getting_started` docs to not repeat analyses

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-docs#117]
From this [comment](https://github.com/AlexsLemonade/scpca-docs/pull/115#pullrequestreview-1468291683):

> More broadly, I think we may want to revisit this whole document to remove most of the filtering and normalization content, as we are now providing that content in the download. It seems odd to suggest simplified versions of these functions, as applying the code here may well result in different results from those that we provide.
>
>Even if the result were the same, I don't think the place to "get started" is with repeating analyses that were already done in the download files! We might keep the same headers but describe how to extract the calculated data that is already there with a brief note about what was done.

**Comment by sjspielman** [comment]
From DSTM 10/10, come back to this after we do CHANGELOG things (#131, #132)

**Comment by allyhawkins** [comment]
Closed by #162
