### ISSUE TITLE
Initialize CHANGELOG

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#131]
We are anticipating updating the sample metadata that is available on the portal (in addition to updating the contents of the SCE objects that are available on the portal). As we anticipate future changes to things on the portal, it might be helpful to include a change log. 

From Deepa: 
> If we are expecting similar metadata changes to happen again in the future,  I was thinking something like release notes, but change log is better since we aren’t really sharing versions explicitly on the portal. In addition to including it downloads, we should have it in the docs with the date.

**Comment by jaclyn-taroni** [comment]
* The CHANGELOG will be in its own section. Tagging @dvenprasad for IA recommendation.
* Initial PR request implementing the CHANGELOG should do the following to satisfy this issue:
  - [ ] Initialize the CHANGELOG Markdown file 
    - [ ] Include language about how the CHANGELOG is a new feature we'll be using moving forward
    - [ ] Include language at the top about where to find `scpca-nf` version information in your download + where to find the `scpca-nf` changelog info
  - [ ] Include CHANGELOG in the correct spot in the index per Deepa's recommendation

**Comment by dvenprasad** [comment]
It should be placed below FAQs. Calling it `CHANGELOG` seems good for now
