### ISSUE TITLE
Add AnnData to download section 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#144]
The [`Downloadable files`](https://scpca.readthedocs.io/en/latest/download_files.html) page must be updated to reflect the new download structure and options. Right now, we have the following sections: 

- `Download folder structure for project downloads`
- `Download folder structure for individual sample downloads`
- `Gene expression data` (this section describes the three files and mentions that they are stored in a SingleCellExperiment object)
- `QC report`
- `Metadata`
- `Multiplexed Sample libraries`
- `Spatial transcriptomics libraries`

I'm proposing that we have the following sections: 

- `SingleCellExperiment downloads` with the following subheaders:
	- `Download folder structure for project downloads`
	- `Download folder structure for individual sample downloads`
- `AnnData downloads` with the following subheaders:
	- `Download folder structure for project downloads`
	- `Download folder structure for individual sample downloads`
- `Gene expression data` 
	- Keep the description about the three files and the contents (e.g., what type of data is stored in unfiltered vs. filtered vs. processed files)
	- Modify the language to note that data is available as either SingleCellExperiment or AnnData objects.
- `QC report` - unchanged 
- `Metadata` - unchanged
- `Multiplexed Sample libraries` - unchanged except to clearly state that multiplexed data is only available as SingleCellExperiment
- `Spatial transcriptomics libraries` - unchanged

This will also involve creating updated images of the download structure for the AnnData files. 

If anyone has any thoughts or other ideas regarding the organization, feel free to comment by EOD 9/26.
Tagging @jaclyn-taroni @dvenprasad and @jashapiro if you have any thoughts.

**Comment by jaclyn-taroni** [comment]
Looks good. I only want to add that the AnnData folder structure might require more illustrations than the SingleCellExperiment section because CITE-seq is handled differently.

**Comment by jashapiro** [comment]
LGTM!

**Comment by allyhawkins** [comment]
Closed by #153
