### ISSUE TITLE
Document contents of AnnData objects

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#145]
Right now we have a page, [`Single-cell gene expression file contents`](https://scpca.readthedocs.io/en/latest/sce_file_contents.html) that discusses all of the components of the `SingleCellExperiment` objects. It has the following structure: 
- `Single-cell gene expression contents`
	- `Components of a SingleCellExperiment object`
	- `Additional SingleCellExperiment components for CITE-seq libraries`
	- `Additional SingleCellExperiment components for multiplexed libraries`

Although there is a lot of repetition in the contents of SCE objects and AnnData objects (since the data is the same). Each of them have different places items are stored and different naming conventions. I think it would make the most sense to have two separate files, one for `Components of a SingleCellExperiment object` and one for `Components of an AnnData object`. 

The structure would look something like this: 
- `Single-cell gene expression contents`
	- `Components of a SingleCellExperiment object`
		- `Additional SingleCellExperiment components for CITE-seq libraries`
		- `Additional SingleCellExperiment components for multiplexed libraries`
	- `Components of an AnnData object`
		- `Additional AnnData components for CITE-seq libraries`

Again, some of the descriptions would be repetitive (like the tables with what's in the metadata), but because of the differences in naming and how to work with both objects, I think separate sections would make the most sense. If anyone has any thoughts or other ideas regarding the organization, feel free to comment by EOD 9/26.
Tagging @dvenprasad @jaclyn-taroni and @jashapiro if you have any thoughts.

**Comment by jaclyn-taroni** [comment]
How different are the naming conventions _within_ the tables that you expected need to be repeated? So, for example, are the names of cell metrics (e.g., `sum`) the same between the two formats?

**Comment by allyhawkins** [comment]
To provide some context, here's a summary of the differences:

- The sample metadata is stored as a separate table in `metadata(sce)` in SCE objects but present as columns in the cell metadata of the AnnData objects. The actual contents are not different though. 
- There are a few additional columns in the cell metadata of the AnnData object that are either not present in the SCE object at all or in different locations (library id, assay ontology term id, suspension type, project id, schema version). 
- The PCs and UMAPs are stored as `X_PCA` and `X_UMAP` in AnnData and `PCA` and `UMAP` in SCE objects.
- The raw counts are stored in the X slot, except for the normalized objects where `logcounts` are stored in the X slot and raw counts in `raw.X`. 
- CITE-seq data is stored in a completely separate file for AnnData.

I think an alternative to making a separate `Components of an AnnData object` would be to expand each subsection to include a description for both SCE objects and AnnData. So under the `Expression counts` section, we would have one section for SCE objects and one section for AnnData objects. Then we can explain any differences between the two files. 

I don't mind this, but I wonder if having the docs separate would make more sense because users will either have downloaded SCE or AnnData, and I think are less likely to download both? Also, we include a link to the gene expression contents file in the README included with the download. It makes sense to me to have two separate files so we could easily link to either SCE or AnnData contents, depending on the download.

**Comment by allyhawkins** [comment]
Closed by #157
