### ISSUE TITLE
Add "How to Cite" section to the docs

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-docs#155]
The section should cover the following information:
- Terms of use: Explain the Terms of Use relating to citing in human-friendly language. 
From section 3 (i) from our Terms of Use
> publish, present or otherwise disclose Data, or results from analysis of Data, obtained through the ScPCADP without properly attributing (i) the Data source using the language provided by the Data contributor of that Data set (as applicable), and (ii) us using the language posted on the ScPCADP or otherwise provided by us;

- Provide a citation for the portal. 
   - Provide APA and MLA format like https://cellxgene.cziscience.com/docs/08__Cite%20cellxgene%20in%20your%20publications
   - Use the organization name ("Alex's Lemonade Stand Foundation Childhood Cancer Data Lab") instead of listing individual contributor names as we do in the refine.bio footer until we preprint/publish.
   - Tell users that they can find the accessed date in the README (to be added) in the download folder. 

- Provide directions to cite individual projects
  - Pointing people to where to find publications and project descriptions for individual projects
  - If no publication is listed, note that the publication information on the Portal might lag and ask people to contact the project contact for more up-to-date information/what they want people to cite.
  - Remind them they can find the link to the project page of the data in the README in the download folder.

**Comment by sjspielman** [comment]
A quick thought I had for content here - we might also want to add a subsection for "What else should you cite if you cite our data?" Thinking tools that we use in the pipeline (e.g. `alevin-fry`) might be worth `h/t`ing here.

**Comment by jaclyn-taroni** [comment]
This is in the feature branch `documentation-improvements`, so I'm going to close this.
