### ISSUE TITLE
Add AnnData docs for citeseq

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-docs#164]
Currently, the `getting_started.md` docs' section on CITE-seq data is specific to RDS files: https://github.com/AlexsLemonade/scpca-docs/blob/29f445099425fc25f1556387a3bf22af80053d9d/docs/getting_started.md?plain=1#L222

We should update this section with `AnnData` information, as needed.

While we're here, might also add something to the multiplexed section about how it is only relevant to RDS files - https://github.com/AlexsLemonade/scpca-docs/blob/29f445099425fc25f1556387a3bf22af80053d9d/docs/getting_started.md?plain=1#L281

**Comment by allyhawkins** [comment]
Just noting that we should wait to do this until changes in #162 are in.

**Comment by sjspielman** [comment]
> Just noting that we should wait to do this until changes in https://github.com/AlexsLemonade/scpca-docs/pull/162 are in.

Added blocker!

**Comment by allyhawkins** [comment]
Closed by #167
