### ISSUE TITLE
Configure ReadTheDocs to use new tags formatted `YYYY.MM.DD` as latest version of docs

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-docs#168]
As scpca-nf and the scpca portal are updated, we are continually updating the documentation. As mentioned in a previous conversation, it would be good if people could easily find prior versions of the documentation, especially in the case when the they downloaded the data at some point in the past and want to see the docs from that time:

> Finally: are we taking advantage of the ability to create versions in readthedocs? This is related to the second point above, but if docs change depending on the version of the workflow run, we might want to keep multiple versions around. Probably something to explore later.

_Originally posted by @jashapiro in https://github.com/AlexsLemonade/scpca-docs/pull/157#pullrequestreview-1671369413_

The scope of this issue includes the following steps:
- [ ] Deciding on a versioning scheme (Dates or semantic versioning?)
- [ ] Documenting a plan/procedure for creating versions of the docs (tags or branches?)
- [ ] Setting up ReadTheDocs to render and display documentation versions

On the first point, I think we had favored dates, but we should discuss below.
On the second, I am agnostic, and curious to hear other's thoughts

On the third: 
ReadTheDocs has functionality to produce versioned docs, either by rendering tags or branches: https://docs.readthedocs.io/en/stable/versions.html

In the docs linked above, it mostly describes manually adding tags to the versions that are displayed, but there is some ability to use automation rules to add tags or branches automatically: 
https://docs.readthedocs.io/en/stable/automation-rules.html 

That seems like it will work easily if we use semantic versions, but custom matches for ISO8601 dates would presumably be straightforward as well.

It appears that this all has to be set in the web interface? It seems like they are not part of the `.readthedocs.yaml` file options (perhaps because these are not version-level settings)

**Comment by jaclyn-taroni** [comment]
To summarize the outcome of our meeting on this topic:

* We want to use ISO 8601 dates as versions (`YYYY-MM-DD`).
* We will be using _tags_ to manage versions.
* We need to set up an automated rule in RTD
  * We need to use a custom match that checks for the date format (e.g., `^20\d\d-[01]\d-\d\d$`)
  * We want the newest tag to be the default view
  * We need to make sure older releases remain active

I'm going to update the title to reflect that this issue now tracks RTD configuration.

**Comment by allyhawkins** [comment]
There is now an automation rule in RTD that matches the regex, `^20\d\d-[01]\d-\d\d$` on tags. The action I used is `Set version as default`, which should build, activate, and set the version as default (see https://docs.readthedocs.io/en/stable/automation-rules.html#actions-for-versions). I believe the only way to test this is to tag a release and see what happens. 

@jaclyn-taroni now that #174 has been merged, I think we are good to do our first release?

**Comment by jaclyn-taroni** [comment]
Yep :shipit:

**Comment by allyhawkins** [comment]
So the tagged version now appears in the dropdown menu, but the portal directs you to the `latest` version of the docs. Which means anything that gets pushed to `main` without a tag will still show up on the `latest` version. This is because the default branch is `main` even though the default version is the new tagged version. I'm trying to figure out how to automatically change the default branch.

**Comment by allyhawkins** [comment]
Actually, I think this is because we are directing people to `https://scpca.readthedocs.io/en/latest/` from the portal. But, if you click on `View Docs` from the RTD interface, the tagged version shows up as the default.

**Comment by jaclyn-taroni** [comment]
It probably makes sense to direct to `https://scpca.readthedocs.io/` from the Portal.

**Comment by jashapiro** [comment]
I think it would be fine not to have it set the default and just use `Activate version`? Then latest is still latest?

**Comment by allyhawkins** [comment]
> I think it would be fine not to have it set the default and just use Activate version? Then latest is still latest?

I'm not sure I understand? Even if we just use `Activate version`, then the `latest` version will still reflect anything in `main`. So if we merge something into `main` before we do a tagged release, then those changes will be shown.

**Comment by jashapiro** [comment]
> > I think it would be fine not to have it set the default and just use Activate version? Then latest is still latest?
> 
> I'm not sure I understand? Even if we just use `Activate version`, then the `latest` version will still reflect anything in `main`. So if we merge something into `main` before we do a tagged release, then those changes will be shown.

Yes, but maybe we want that? Or not. As long as the `latest` is still there, your choice is probably reasonable!

**Comment by jaclyn-taroni** [comment]
I changed the title to reflect what is currently in RTD, and to summarize here as well: we're not using `YYYY.MM.DD` for tag format so it "looks like" a semantic version to RTD. I will now close this.

**Comment by jashapiro** [comment]
> I changed the title to reflect what is currently in RTD, and to summarize here as well: we're not using `YYYY.MM.DD` for tag format so it "looks like" a semantic version to RTD. I will now close this.

"now using"?

**Comment by jaclyn-taroni** [comment]
Yes, now using.
