### ISSUE TITLE
Change code link colors?

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-docs#170]
I noticed that inline code formatted text looks the same whether it's a link or just regular text. For example, these will have the same styling in `readthedocs` - 

- [`SingleR`](https://bioconductor.org/packages/release/bioc/html/SingleR.html)
- `SingleR`

Maybe we need to incorporate some different styling so in-line code formatted text that is a link clearly appears as a link?

**Comment by sjspielman** [comment]
I wonder if this something worth including in one of the upcoming releases. @dvenprasad, do you have any thoughts here on a) whether this is worth pursuing, b) how soon makes sense to pursue this, and c) if (a) is true, what color 🎨 ?

**Comment by dvenprasad** [comment]
Users not being able to recognize links when enclose in backticks came up in evals of scpca-nf and downstream analyses but Github generously made that distinction for us. 

So yes, if it is a simple and easy fix, we can include it in one of the upcoming docs releases. The link color should be blue (#003595). If it isn't possible to specify the color, the generic internet blue for links also works.

**Comment by sjspielman** [comment]
I confess, with my limited `css` skills, I thought popping something as simple as 
```
.pre a {
  color: #003595;
}
```

into `style.css` would work, but alas. Then I did more silly things like all combinations of 

a .reference-external .docutils-literal-notranslate .pre {
  color: #003595;
}

(inspired by this line of source code....)
```
<a class="reference external" href="https://alevin-fry.readthedocs.io/en/latest/"><code class="docutils literal notranslate"><span class="pre">alevin-fry</span></code></a>
```

So, surprising no one, I have come to the conclusion that someone who _actually_ knows css should take this over!
