### ISSUE TITLE
Add changelog entry that includes information about added AnnData

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#189]
The downloads from the portal will soon be available as either AnnData or SCE objects. The following should be noted in the changelog entry: 

- Data is now available as either SingleCellExperiment/RDS or AnnData/HDF5 files. This applies to all libraries except for multiplexed and spatial. 
- Ontology terms are now included in the metadata with each download 
- Cluster assignments are now available for libraries. I don't know if we should include this in the changelog because it means a new plot in the QC report, but do we want people to use these clusters? 🤷‍♀️ I'm just adding it to this list so we don't forget clusters are also being added. 
- Participant IDs have now been added for all samples. These used to be NA for most samples that only came from a single participant. 
- All sample metadata is now stored in the actual objects themselves (I'm 50/50 on if this is important enough for changelog. I think it's nice to tell users now that they can directly access metadata in the object since they couldn't do that before.) 

This entry should be added after the entry mentioned in #187.

**Comment by allyhawkins** [comment]
We might also want to mention that submitter cell types are present in the objects for any projects that submitted cell types. But that's only one project and we are going to release all the cell type information next, so not totally necessary.

**Comment by sjspielman** [comment]
I'm assuming some of these updated names like `_qc_report.html` -> `report.html` are incoming here? Or are they incoming in cell typing (#209)? We should probably get it into the right CHANGELOG spot.

**Comment by allyhawkins** [comment]
> I'm assuming the updated name `_qc_report.html` -> `report.html` is incoming here? Or is it in cell typing (#209)? We should probably get it into the right CHANGELOG spot.
> 
> *Edited since this is the only relevant one that might be incoming here.

It was actually always `_qc.html` and we just had it wrong in the illustrations. So no need to make any updates.

**Comment by sjspielman** [comment]
> we just had it wrong in the illustrations.

Ha! woops..

**Comment by allyhawkins** [comment]
Closed by #207
