### ISSUE TITLE
Remove FAQ about missing participant IDs

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#190]
When we add AnnData in the portal, we will also be adding participant IDs for all samples. Right now we have a [FAQ: Why do some samples have missing participant IDs? ](https://scpca.readthedocs.io/en/latest/faq.html#why-do-some-samples-have-missing-participant-ids), that should probably get updated. 

I think we might want to replace this with a FAQ on what is a participant ID.

**Comment by jaclyn-taroni** [comment]
Good catch!

**Comment by allyhawkins** [comment]
Closed by #203
