### ISSUE TITLE
Update how we describe submitter annotations

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-docs#194]
> This plan also sounds good to me. Just to note that we should update this section of the sce contents in the user facing docs to reflect this (https://github.com/AlexsLemonade/scpca-docs/blob/development/docs/sce_file_contents.md) <img alt="Screenshot 2023-11-09 at 8 35 38 AM" width="828" src="https://user-images.githubusercontent.com/54039191/281766157-26b1c3c3-69fd-422d-866e-5ea26860cf48.png">

_Originally posted by @allyhawkins in https://github.com/AlexsLemonade/scpca-nf/issues/454#issuecomment-1803950078_

**Comment by jaclyn-taroni** [comment]
Closed by #213
