### ISSUE TITLE
Add CHANGELOG entry for cell type annotation

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-docs#209]
The downloads from the portal will soon contain cell type annotations.  The following should be noted in the `CHANGELOG` entry:

- Objects, both SCE and AnnData, now contain cell type annotations as performed by `SingleR` and `CellAssign`.
- References used for cell typing and their versions are also provided within the objects.
	- (Not sure if we want to include this?) The full results returned by `SingleR` are provided in the SCE objects, and the full results returned by `CellAssign` are provided in both SCE and AnnData objects.
- `SingleR` annotations are only provided both as cell type labels and cell type ontology IDs, but `CellAssign` annotations are only provided as cell type labels.
- An additional cell type report is provided with more in-depth information about cell type annotations, including comparisons between different cell type annotations and diagnostic assessments of cell type annotation reliability. 

This should be added after the `CHANGELOG` entry described in #189.

(Edit) - noting we probably don't need to include this bullet I originally had since submitter annotations will have been added with the AnnData release. That bullet is here for posterity:
> - Certain projects will additionally contain cell type annotations as determined & provided by the project submitters themselves.

**Comment by sjspielman** [comment]
Note to self, close this out only once the _date_ has been formally added to the CHANGELOG.

**Comment by allyhawkins** [comment]
Closed by #189
