### ISSUE TITLE
Add "Working with merged objects" to getting started section

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-docs#216]
We would like to demonstrate how you can use merged objects for integration in the _Getting started with an ScPCA dataset_ section. My IA suggestion: place this directly after _Working with processed objects_ in `docs/getting_started.md`.

**Comment by sjspielman** [comment]
Noting I've gotten started on this here: https://github.com/AlexsLemonade/scpca-docs/tree/sjspielman/216-getting-started-merged

I think we should maybe discuss a little more what we'd like to present. Some thoughts:

- How to subset to a given set of libraries of interest
- How to run integration with an R method - maybe just stick with `fastMNN`? We want to avoid specifically endorsing a given integration method I think, so language should probably emphasize that this is only an example of how one MIGHT integrate, not how one SHOULD integrate.

Are there any other ideas that people have in mind?

**Comment by allyhawkins** [comment]
> How to run integration with an R method - maybe just stick with fastMNN? We want to avoid specifically endorsing a given integration method I think, so language should probably emphasize that this is only an example of how one MIGHT integrate, not how one SHOULD integrate.

I don't know that we actually want to provide code to perform integration. I think we just need to include a section that you might want to integrate these samples in order to perform specific downstream analyses (e.g. clustering). Then we can provide links to integration information, like the section in OSCA, which I believe does talk about `fastMNN`. I would focus more on the purpose of integration (is there one? not always...) rather than the code to actually do it.

**Comment by sjspielman** [comment]
> I don't know that we actually want to provide code to perform integration. I think we just need to include a section that you might want to integrate these samples in order to perform specific downstream analyses (e.g. clustering). Then we can provide links to integration information, like the section in OSCA, which I believe does talk about fastMNN. I would focus more on the purpose of integration (is there one? not always...) rather than the code to actually do it.

I agree with this 100%! Right now I have code in there showing how to read in & subset, and maybe that's really all we should show.

**Comment by sjspielman** [comment]
Closed by #230
