### ISSUE TITLE
Add a merged objects section to Downloadable files

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-docs#217]
We need to describe what merged object downloads will be like in the Downloadable files section and include illustrations (SCE, AnnData, and CITE-seq).

**Comment by sjspielman** [comment]
From slack conversation with @dvenprasad:

> For download files: If we decide to make merged objects a separate page, then we should tuck the downloadable files for merged objects under a Merged objects section on downloadable files page so we’re being consistent with that distinction.

But where should this section go?

> We can just insert that section after AnnData - and show both SCE merged and AnnData merged.

**Comment by sjspielman** [comment]
Noting I'm assigning myself here for the description part, and @dvenprasad for the illustration part. We can also break this up into two issues if that's preferred!

**Comment by sjspielman** [comment]
Ah I see #218 was already broken out for issues! Congratulations @dvenprasad, I'm removing you here and instead blocking this with #218.

**Comment by dvenprasad** [comment]
@sjspielman The illustrations are done. Let me know if anything is missing on #218

**Comment by sjspielman** [comment]
Closed by #234
