### ISSUE TITLE
Establish new docs page for merged object contents

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-docs#219]
Nothing about the Single-cell gene expression file contents section was noted in our meeting notes. I am filing this WIP issue to ensure we discuss whether or not a change to this section is required the next time we plan a sprint.

**Comment by sjspielman** [comment]
From Slack chat with @dvenprasad:

> Merged objects should be its own page (and be one of the top level navigation items too). On the portal, we treat merged objects as separate option from the data format and keeping that same distinction in the docs will be helpful for both consistency and linking users to the right section from the download options help button.

So, nothing will need to change in `sce_file_contents.md`. Instead, we'll want to create a whole new file.

**Comment by sjspielman** [comment]
Seeking an opinion on how in-depth this page should go (@dvenprasad @allyhawkins). I am thinking of two broad options:

1. We can effectively mirror the text in `sce_file_contents.md` for all relevant sections. The benefit of this is that it allows users to _only have to read_ these merged file contents docs if that is what they chosen to download. The drawback is substantial repetition between documents (but is this actually a drawback?).  Just as a miscellaneous example, even text like this would be adapted into this new merged file with text updated to reflect merged contents: https://github.com/AlexsLemonade/scpca-docs/blob/d7c2b4db3c75eb08530518c103fa23afc090ab8c/docs/sce_file_contents.md?plain=1#L9-L24
 
2. We can focus on highlighting the differences of a merged object from an individual-library object, with much less repetition. The text I linked above would not be precisely replicated at all; instead, we might just say something along the lines of "the merged object contains expression counts, as described in \<link that sce_file_contents section\>, except it has these differences from an individual-library object: ...."

**Comment by sjspielman** [comment]
> The text I linked above would not be precisely replicated at all; instead, we might just say something along the lines of "the merged object contains expression counts, as described in <link that sce_file_contents section>, except it has these differences from an individual-library object: ...."

Followup to this - linking means they would have to go back and forth between pages _ a lot_, which is probably very annoying for users.

**Comment by sjspielman** [comment]
Notes to self:

Don't forget that we only keep these `colData` columns:
https://github.com/AlexsLemonade/scpcaTools/blob/2ebdc4f4dfc4233fad97805f9a9a5e3bc6919f1e/R/merge_sce_list.R#L50C5-L60

As well as these if citeseq:
https://github.com/AlexsLemonade/scpcaTools/blob/2ebdc4f4dfc4233fad97805f9a9a5e3bc6919f1e/R/merge_sce_list.R#L97C25-L104

And then we add in `library_id` and `cell_id`:
https://github.com/AlexsLemonade/scpcaTools/blob/2ebdc4f4dfc4233fad97805f9a9a5e3bc6919f1e/R/merge_sce_list.R#L286-L290

**Comment by sjspielman** [comment]
This page has been established, so I'm going to close this issue in favor of #240 and #241 which track fleshing out the page in full.
