### ISSUE TITLE
FAQ: Why is a merged object unavailable for this project?

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-docs#221]
You can't get a merged object if you're downloading a spatial project download. We must explain why a merged object is unavailable in these cases and any others. The other example I'm aware of is AnnData project downloads when a project _exclusively_ comprises multiplexed samples, but I don't believe we currently have anything that fits that criterion.

**Comment by sjspielman** [comment]
Closed by #255
