### ISSUE TITLE
Document missing cell types for cell lines

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#222]
We will not be performing cell type annotation for any samples that come from cell lines. We will want to be sure to note this when describing cell type annotation.

**Comment by sjspielman** [comment]
Related, we'll need to tell people how they can determine if their sample is a cell line. This can be found in the sample metadata, which we'll document as part of #227

**Comment by sjspielman** [comment]
Closed by #228
