### ISSUE TITLE
Corrected download folder images

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-docs#226]
QC and Cell Type reports in the illustration did not match how they were named in the the downloads. Here are the illustrations with those corrections. 

**SCE Project Download**
![sc-project-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/008ed6b8-ee93-4eb3-a8cb-d4274d3a8d3d)

**SCE Sample Download**
![sc-sample-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/0b141258-e5b3-41f7-b5b4-6617b2d8718c)

**AnnData Project Download**
![anndata-project-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/9325ed4e-596b-4d3a-a5f3-a03e3edb015c)

**AnnData Sample Download**
![anndata-sample-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/39f1f0df-bce6-4c30-9802-70ca4644af75)

**AnnData CITE-seq Sample Download**
![anndata-CITE-seq-sample-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/9d230f10-870f-4b4c-88f2-61b4f7a82e8a)

**Multiplexed Download**
![multiplexed-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/13b71751-620e-409b-b761-1f1646091aab)

@allyhawkins Let me know if you need anything else or if I've missed anything.

**Comment by allyhawkins** [comment]
This should be everything, but since we are changing the cell type report to match what @jashapiro suggested, the second `_` should be `-`. So it should be `SCPCL000000_celltype-report.html`.

**Comment by dvenprasad** [comment]
Here are the updated ones

**SCE Project Download**
![sc-project-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/1564b26a-a452-4a8d-aed1-d766cef5fd0b)

**SCE Sample Download**
![sc-sample-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/639f0953-f21e-4b1e-b018-8b74c67d2461)

**AnnData Project Download**
![anndata-project-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/ce717afa-5b55-4899-b4f6-0790153306bd)

**AnnData Sample Download**
![anndata-sample-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/2c8dbefb-3ba1-4940-9dce-7683c63b22c0)

**AnnData CITE-seq Sample Download**
![anndata-CITE-seq-sample-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/cec99fec-69af-4d0e-9466-816cf85461d4)

**Multiplexed Download**

![multiplexed-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/e6d14d87-0a98-4e83-a5f2-c69214760129)

**Comment by allyhawkins** [comment]
Amazing thanks Deepa! I'll go ahead and incorporate these.

**Comment by sjspielman** [comment]
These were merged in with #232, so we can close this out now.
