### ISSUE TITLE
Update download images: single_cell_metadata is a tsv, not csv

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-docs#238]
While working on merged docs, I noticed a _general discrepancy_ between _all_ of our images and the actual downloads themselves.

- All of our download images indicate a metadata file (caps for emphasis) `single_cell_metadata.CSV`, but the actual file itself is a `single_cell_metadata.TSV`. I confirmed this by downloading a sample from the portal.
  - See images here (same situation in the `development` branch) : https://github.com/AlexsLemonade/scpca-docs/tree/main/docs/images 
- The docs themselves state that it is a TSV, as well: https://github.com/AlexsLemonade/scpca-docs/blob/d7c2b4db3c75eb08530518c103fa23afc090ab8c/docs/download_files.md?plain=1#L67 

So, I suppose we need to update all of the images with the correct extension. 
FYI @dvenprasad

**Comment by dvenprasad** [comment]
![sc-project-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/c65e75fb-3af1-45b6-9cf1-76ba063445fb)

![sc-sample-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/66c2dac5-a18f-4fe5-875d-23298f51ea80)


![anndata-CITE-seq-sample-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/a579e03b-1522-49a2-8b17-569598f6661e)
![anndata-sample-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/6db45d1a-f7ff-4f16-a7f7-95b5e63c5dd1)

![multiplexed-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/0d9391fa-9a75-419e-9fbe-30b761d96156)
![anndata-project-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/03fb0f36-3ebc-4ee3-9648-dbe4d094eed8)

**Comment by sjspielman** [comment]
I compared each image in https://github.com/AlexsLemonade/scpca-docs/issues/238#issuecomment-1908900627 to the existing images, and the only difference I see is indeed we now have a `tsv` instead of `csv` where expected.

**Comment by sjspielman** [comment]
@dvenprasad SHOCKING UPDATE. Can we also -> `csv` -> `tsv` in the `spatial-download-folder.png`?

Should be `spatial_metadata.TSV`? (caps for emphasis) 🙃

**Comment by dvenprasad** [comment]
**Spatial Project Download**
![spatial-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/7ac21541-533a-434c-a08e-197374a6783a)

**Comment by sjspielman** [comment]
Closed by #257
