### ISSUE TITLE
FAQ: How do I get the link for a download?

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-docs#259]
If someone wanted to download data directly to their server, it'd be helpful for them to be able to get the link to download. The easiest way for someone to accomplish this is to cancel the download in their browser and copy the link used to fetch the file. This FAQ should also note that the links do expire a week after generating.

**Comment by sjspielman** [comment]
I just went to test this out to prepare to write an FAQ for it, but I did not find it feasible! I tested it in both Firefox and Safari. In firefox, the download URL flashed by _way_ too fast to be able to copy/paste it out (see attached video). In Safari, the download URL never even seemed to appear in the first place.

https://github.com/AlexsLemonade/scpca-docs/assets/4701111/1056b501-589f-4c2d-846e-f089fd244f85

**Comment by sjspielman** [comment]
woops, meant to also ping @davidsmejia - thoughts?

**Comment by jashapiro** [comment]
Right click on "Try Again" to get the download link

**Comment by dvenprasad** [comment]
We are providing a mechanism for folks to copy the link from the interface. Closing this in favor of https://github.com/AlexsLemonade/scpca-docs/issues/345
