### ISSUE TITLE
Pick one: ID or id

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-docs#265]
While working on docs, I noticed that we tend to hop around between `ID` and `id`. We should maybe pick one?

**Comment by jashapiro** [comment]
In my quick [search of the released docs](https://github.com/search?q=repo:AlexsLemonade/scpca-docs%20id&type=code) in `main` I see only one use of `id` in text, so we should probably stick with `ID`, except when referring to code variables, where we should use what is there (almost always `id`

**Comment by sjspielman** [comment]
>  so we should probably stick with "ID", except when referring to code variables, where we should use what is there (almost always id)

When you say "referring to code variables," do mean for example when referring to "sample_id" we should use "id"? Most places are already using "ID" in those spots. Or, are you talking about the actual variables themselves?

**Comment by jashapiro** [comment]
Just the actual variables, some of which are `id`

**Comment by sjspielman** [comment]
> Just the actual variables, some of which are id

Great, that's what I thought. Definitely don't want to touch those!!

**Comment by sjspielman** [comment]
Closed with #266
