### ISSUE TITLE
Add CHANGELOG entry for merged release

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-docs#268]
Change include:

- Projects can now be downloaded either as individual objects for each library or as a single object containing all merged libraries, either in SCE or AnnData formats
- All contents of objects are merged, except for HTO counts
  - (is this too much detail?)
- Merged downloads will contain a report briefly summarizing contents of merged objects, as well as the individual QC and celltype reports for all libraries in the merged object

**Comment by allyhawkins** [comment]
Closed by #284
