### ISSUE TITLE
Update sample_type description in docs

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-docs#276]
In https://github.com/AlexsLemonade/scpca-nf/issues/713, we're going to update the `sample_type` metadata. 
Once that is set, we should update here accordingly.

https://github.com/AlexsLemonade/scpca-docs/blob/aa3887cdd3d0ab8ea31b618b57d77f731b5a951a/docs/sce_file_contents.md?plain=1#L138

**Comment by allyhawkins** [comment]
Closed by #277
