### ISSUE TITLE
Update file list images for h5ad

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-docs#288]
In coordination with #287, we will need to update the following files in the `images` directory to change all mentions of `.hdf5` to `.h5ad`

- `anndata-project-download-folder.png`
- `anndata-sample-citeseq-download-folder.png`
- `anndata-sample-download-folder.png`
- `merged-anndata-project-citeseq-download-folder.png`
- `merged-anndata-project-download-folder.png`

This will finish docs updates related to https://github.com/AlexsLemonade/scpca-nf/issues/736

**Comment by dvenprasad** [comment]
**anndata-project-download-folder.png**
![anndata-project-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/c0e97ed3-f22b-4d30-9c07-7eaa2a022faa)

**anndata-sample-citeseq-download-folder.png**
![anndata-CITE-seq-sample-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/9ac0248e-36f7-47fe-a4d2-c48b2b9b6a33)

**anndata-sample-download-folder.png**
![anndata-sample-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/00d1bbe7-457a-4506-af7c-5f015284d068)


**merged-anndata-project-citeseq-download-folder.png**
![merged-anndata-cite-seq-project-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/1f0616c2-8414-407b-a20c-f8ea93dde500)

**merged-anndata-project-download-folder.png**
![merged-anndata-project-download-folder](https://github.com/AlexsLemonade/scpca-docs/assets/15315514/5f1b25b3-690d-4f48-8561-345546520bb1)

**Comment by jashapiro** [comment]
Thank you @dvenprasad !

**Comment by jashapiro** [comment]
closed by #287
