### ISSUE TITLE
Add CHANGELOG for transition to `.h5ad` extensions

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-docs#294]
Change includes `.hdf5` -> `.h5ad` in AnnData downloads.

**Comment by jashapiro** [comment]
This is already present in `development`: https://github.com/AlexsLemonade/scpca-docs/blob/development/docs/CHANGELOG.md

**Comment by jaclyn-taroni** [comment]
I will take this opportunity to state that this transition didn't involve enough issues for my taste.
