### ISSUE TITLE
Add sample metadata file to Downloadable files section

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-docs#309]
Add a subsection under `Downloadable Files` section explaining the sample metadata file and its contents. This is for the project level metadata file.

**Comment by allyhawkins** [comment]
From https://github.com/AlexsLemonade/scpca-portal/issues/717#issuecomment-2124867406: 

> > For this I think we should add a section to the docs for unified metadata, not sure about naming. We could expand on the expected values here but it would be nice to not have to keep the docs and this README in sync.
Something like this: https://scpca.readthedocs.io/en/stable/download_files.html#metadata

> Yes, I definitely agree that we would want a full version of the included metadata in the docs. You could then just link to that table or section of the docs in the contents section.

Based on this we should be sure to include a full table with all columns that will be found in every metadata download.

**Comment by allyhawkins** [comment]
Closed by #313
