### ISSUE TITLE
Reduce size of "Download folder structure" images

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-docs#316]
Looking at https://scpca.readthedocs.io/en/stable/download_files.html#download-folder-structure-for-singlecellexperiment-merged-downloads, and other sections of the docs, the images seem oversized, distractingly so. We should perhaps reduce those so that the text size roughly matches the rest of the text on the page.

The images themselves are quite a bit larger than they need to be: I would suggest shrinking the source images to 800px wide and displaying them at 400 px wide.

**Comment by allyhawkins** [comment]
Closed by #329
