### ISSUE TITLE
Change log entry for new age columns

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#327]
We will need a change log entry that recaps the changes to the age column: 

- The `age_at_diagnosis` column is being renamed`age`
- Add new `age_timing` column that has either `diagnosis`, `collection`, or `unknown`.

**Comment by allyhawkins** [comment]
Note that this will also include new changes for scanpy compatibility.

**Comment by jaclyn-taroni** [comment]
I'm going to set this as blocked by #339.
