### ISSUE TITLE
Update docs to account for new folder name for downloads

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#339]
In looking at the most recent data upload, I noticed that the folder name for downloads does not quite match what's in the docs. In general the folder name has the following format: `ID_MODALITY_FORMAT_DATE`, for example `SCPCS000001_SINGLE-CELL_SINGLE-CELL-EXPERIMENT_DATE`. 

We need to update the images in the download files section to include this new format for the folder name. Tagging @dvenprasad to help with creating the updated images. 

I don't believe there are any text changes for this, just image changes. 

@davidsmejia is also going to update the folder names on the Portal so that they have `_` to separate sample, modality, format, and date but `-` to separate the words like `single-cell` and `single-cell-experiment`.

**Comment by jaclyn-taroni** [comment]
I would expect the CHANGELOG text to report this change.

**Comment by davidsmejia** [comment]
Link to the updated outputs here for reference:

https://github.com/AlexsLemonade/scpca-portal/pull/845#issuecomment-2285032492

**Comment by dvenprasad** [comment]
@jaclyn-taroni lmk if you need anything else or need me to tweak anything.

**AnnData CITE-seq Sample**
![anndata-CITE-seq-sample-download-folder](https://github.com/user-attachments/assets/36e98287-ea21-494d-9673-64e91f971331)

**AnnData Project**
![anndata-project-download-folder](https://github.com/user-attachments/assets/072ae780-d4fd-480f-8242-41fb99bc8191)

**AnnData Sample**
![anndata-sample-download-folder](https://github.com/user-attachments/assets/83714e56-86b0-4fab-83f3-c94fcd76c4b6)

**AnnData Merged CITE-seq Project**
![merged-anndata-cite-seq-project-download-folder](https://github.com/user-attachments/assets/19222dd4-6305-45a2-a333-67cc8bf4f252)

**AnnData Merged Project**
![merged-anndata-project-download-folder](https://github.com/user-attachments/assets/05d6af63-7d59-49ea-b8cd-abd32e31987d)

**SCE Merged Project**
![merged-sc-project-download-folder](https://github.com/user-attachments/assets/2aaeb7c3-f151-4f49-ae98-ba52f2eaab34)

**SCE Multiplexed Project**
![multiplexed-download-folder](https://github.com/user-attachments/assets/1f001555-b4f2-4ef3-82f2-e04bd2e1507a)

**SCE Project**
![sc-project-download-folder](https://github.com/user-attachments/assets/3e55dacf-7c9a-4845-a43d-e256f1b47e5a)

**SCE Sample**
![sc-sample-download-folder](https://github.com/user-attachments/assets/7e5ac8d6-d6cf-40cd-8f70-c14a2eb8083b)

**SCE Spatial**
![spatial-download-folder](https://github.com/user-attachments/assets/fe825efb-64f3-48cf-bc07-fa564d551a64)

**Comment by jashapiro** [comment]
I would expect ANNDATA to be one word?

**Comment by jaclyn-taroni** [comment]
That's a later conversation, @jashapiro, not a today conversation.
