### ISSUE TITLE
Update alevin-fry's references

### ISSUE THREAD

**Issue by DongzeHE** [AlexsLemonade/scpca-docs#347]
Dear scPCA team,

Thank you very much for brining scPCA to the community and choosing alevin-fry as the preprocessing tool! 

I saw that the reference to alevin-fry might be outdated. It currently points to the preprint [He et al. 2021] (https://doi.org/10.1101/2021.06.29.450377) instead of our peer-reviewed paper [He et al. 2023](https://doi.org/10.1038/s41592-022-01408-3). It will be great if these references could be updated. Please let me know if you want me to submit a PR with the updated links! 

Best,
Dongze

**Comment by jaclyn-taroni** [comment]
Hi @DongzeHE, thanks for bringing this to our attention! We would welcome a pull request to update these references.
