### ISSUE TITLE
Change in bulk file names

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-docs#368]
When looking into #367 and trying to understand missing events in https://github.com/AlexsLemonade/OpenScPCA-nf/pull/102, I saw that the names for the bulk files have changed. Where they were before named `bulk_metadata.tsv` and `bulk_quant.tsv`, they are now prefixed with the project name:  e.g., `SCPCP000001_bulk_metadata.tsv`, etc.

This change is not reflected in the docs, so we should update the docs. (I like the change, but was not aware of it.)

https://github.com/AlexsLemonade/scpca-docs/blob/2ea40c44eb34a53d297edde57bc25d7eb9a8718d/docs/download_files.md?plain=1#L29-L31

**Comment by jaclyn-taroni** [comment]
I bet that the same update as described here is responsible: https://github.com/AlexsLemonade/scpca-docs/blob/main/docs/CHANGELOG.md#20240813

We should address what you've identified here and perhaps make the CHANGELOG entry more general (or at least give the bulk example, too).

**Comment by jaclyn-taroni** [comment]
We need to change the images, too, unfortunately.

**Comment by jaclyn-taroni** [comment]
@davidsmejia - do you know when this changed? I'm trying to understand if we need to correct an existing CHANGELOG entry or add a new one.

**Comment by davidsmejia** [comment]
> @davidsmejia - do you know when this changed? I'm trying to understand if we need to correct an existing CHANGELOG entry or add a new one.

This change was deployed on 2024-07-31. This would have been part of the changes that were updated / documented in 2024-08-13. But the original change landed in the previous portal release / docs change.
