### ISSUE TITLE
Create user facing documentation describing processing for single-cell and single-nuclei alevin-fry pipeline

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#4]
Since we have settled on using alevin-fry and started to create the workflow, we should write the documentation to help future us. This should go in it's own repo `scpca-docs` and use RTD, but until that gets created adding this issue here.

**Comment by jaclyn-taroni** [comment]
Closed by #3?

**Comment by jaclyn-taroni** [comment]
Was this closed by #3 @allyhawkins?

**Comment by allyhawkins** [comment]
Yes, will close this.
