### ISSUE TITLE
Create a "Getting started with an ScPCA dataset" section

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-docs#52]
#### Context

We want to make it easier for folks to get started with the files they've downloaded. We can assume that the initial audience for this page in the docs are: familiar with R, including reading files in, but perhaps new to working with the relevant data modalities and with `SingleCellExperiments` specifically.

#### Idea

This should be it's own document (markdown file) that comes after `Single-cell gene expression file contents` but before `Frequently Asked Questions` in the sidebar, in my opinion. I'm open to alternative titles for this section.

It will link out to other resources for working with single-cell data (e.g., [OSCA](https://bioconductor.org/books/release/OSCA/), ) and if there are any steps required for preparing the data to use with any linked resources, we can put that on the page as well (e.g., code snippets).

**Comment by jaclyn-taroni** [comment]
For this sprint, we're aiming for the minimum viable product version of this. To be expanded as we get feedback from users.

**Comment by allyhawkins** [comment]
Based on our discussion, this initial version of this section should include information on how to read the `RDS` files into R and how to convert to a Seurat object if interested. We will then provide informative links to working with SCE's (like [OSCA](https://bioconductor.org/books/release/OSCA/)) and Seurat objects. We will also provide links to perform the typical next steps in SCE analysis - QC filtering, normalization, and dimensionality reduction. 
We might also want to mention as part of this that we have already done some QC filtering so they could use the `miQC_pass` column to perform filtering and show an example. 
If there is anything I missed (or misinterpreted from our discussion) please comment here, so I can be sure to incorporate it while working on this issue.
