### ISSUE TITLE
Update screenshots in download section to reflect name change of libraries_metadata.tsv to single_cell_metadata.tsv 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#57]
Related to changes in #56, we have changed the name of the `libraries_metadata.csv` that is included in the download from scpca to be `single_cell_metadata.tsv`. This change should be reflected in the screenshots for downloading by [project](https://github.com/AlexsLemonade/scpca-docs/blob/main/docs/download_files.md#download-folder-structure-for-project-downloads) and downloading by [sample](https://github.com/AlexsLemonade/scpca-docs/blob/main/docs/download_files.md#download-folder-structure-for-individual-sample-downloads) as that file is present in both. 

The PR with the screenshot changes should be stacked on #56 so that we can merge all changes at the same time and not have conflicting information available in the docs.

**Comment by dvenprasad** [comment]
![project-download-folder](https://user-images.githubusercontent.com/15315514/156806533-f45e1bef-9a96-490d-b9ad-5aabec2d28a2.png)
![sample-download-folder](https://user-images.githubusercontent.com/15315514/156806534-7ef8d56b-f8f9-4458-b3f5-3f0f42cb7ede.png)

**Comment by allyhawkins** [comment]
Closed by #58
