### ISSUE TITLE
Section: Download files

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-docs#6]
Talk about what user can expect in their download files and how it is structured.

Probably also needs illustration of the file structure.

**Comment by allyhawkins** [comment]
Based on our conversation in the scpca standing meeting, we may also want to include some basic R and python code on how to read in these files in this section.

**Comment by dvenprasad** [comment]
![download-folder](https://user-images.githubusercontent.com/15315514/142041878-cfc0a3e7-86dd-46a9-9835-8cec35fe8e32.png)

**Comment by dvenprasad** [comment]
Ignore the previous one. It is incorrect. 

**Project Download Folder**
![project-download-folder](https://user-images.githubusercontent.com/15315514/142902842-6dcea60a-e7d8-4dfa-8de1-aebb581109c8.png)


**Sample Download Folder**
![sample-download-folder](https://user-images.githubusercontent.com/15315514/142902843-fcdabcf0-ea7b-4e05-b436-e8c93b880560.png)

**Comment by jaclyn-taroni** [comment]
Can this get closed?
