### ISSUE TITLE
Add metadata.json file to description of spatial outputs

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#69]
Since we are now including the `SCPCL000000_metadata.json` file in the download for a spatial library and it will be included in the spatial folder for each library, it will need to be added to the list of files that are expected in the download listed in the [Spatial transcriptomics section](https://github.com/AlexsLemonade/scpca-docs/blob/main/docs/download_files.md#spatial-transcriptomics-libraries).

**Comment by jaclyn-taroni** [comment]
Closed via #71.
