### ISSUE TITLE
Document download structure for multiplex samples

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-docs#75]
This is beginning to firm up. For now, I want to make sure we track adding it to the documentation!

**Comment by jaclyn-taroni** [comment]
@dvenprasad do you think we need another illustration for the multiplex downloads? We expect the overall folder structure to be the same, but the folder/directory names will reflect multiple samples.

**Comment by dvenprasad** [comment]
<img width="405" alt="multiplexed-download-folder" src="https://user-images.githubusercontent.com/15315514/176923680-3a2049e2-d9e3-4187-a129-4e47aeabf049.png">


Does this look accurate?

**Comment by jashapiro** [comment]
> <img alt="multiplexed-download-folder" width="405" src="https://user-images.githubusercontent.com/15315514/176923680-3a2049e2-d9e3-4187-a129-4e47aeabf049.png">
> 
> Does this look accurate?

I think so, mostly. I was not sure if the dev team was planning to change the format from commas to underscores, but if they are, that is great. Do we need three sets of libraries though, I wonder?

**Comment by jashapiro** [comment]
Can @arkid15r or @davidsmejia comment on whether the folder names with "sample sets" will be converted to use underscores for the downloads? I am in favor of that, in general, but I wanted to check if it is the current plan as we finalize the figure above & the docs.

**Comment by davidsmejia** [comment]
This looks correct to me for projects (underscores instead of commas).

**Comment by jashapiro** [comment]
> This looks correct to me for projects (underscores instead of commas). Should bulk be part of the multiplexed download?

Thank you. Yes, bulk should still be part of multiplexed project downloads (which may contain non-multiplexed data as well!)
