### ISSUE TITLE
Add processing information for normalization and UMAP

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-docs#90]
As we add normalization & UMAP display to the workflow and post new objects with those data, we will want to explain both the processing choices and SCE file content for the updated files. I am filing this as a single issue for now, but depending on scope we may want to split the processing and file content changes into separate issues down the line.

**Comment by allyhawkins** [comment]
Updating the title of this issue to reflect that this should be used to add a description of any processing related decisions to the docs related to filtering, normalization, and dimensionality reduction to produce the `_processed.rds` file.

**Comment by allyhawkins** [comment]
Closed by #97
