### ISSUE TITLE
Update project and sample download files illustrations to include `_processed.rds` file

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#95]
All single-cell and single-nuclei samples being downloaded will now have an additional file included in the sample folder, `<library_id>_processed.rds`. This file should be included in the illustrations of the download for a project and for a sample in `download_files.md`.

**Comment by jaclyn-taroni** [comment]
Tagging @dvenprasad

**Comment by dvenprasad** [comment]
<img width="293" alt="sc-sample-download-folder" src="https://user-images.githubusercontent.com/15315514/197820844-b85ada1b-d744-4135-bb9f-0110658d6deb.png">
<img width="339" alt="sc-project-download-folder" src="https://user-images.githubusercontent.com/15315514/197820849-337d8721-def1-42c5-ba1c-62416f92f828.png">


@allyhawkins Are these accurate?

**Comment by allyhawkins** [comment]
Yes thank you @dvenprasad!

**Comment by allyhawkins** [comment]
Closed by #99
