### ISSUE TITLE
Update getting started section to include processed.rds file

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#98]
Now that we are going to have a `_processed.rds` file that users can download we probably will want to update the getting started section. Currently the steps that are outlined in the getting started section are for the most part the same steps that we are taking when we create the `_processed.rds` file. We probably want to keep those steps there in case users still want to work with the `_filtered.rds` file, but we should clarify which file the instructions are intended for. 

We also might want to consider expanding to include specific instructions for working with the `_processed.rds` file, e.g. moving onto clustering. But that can get complicated... so maybe instead we add another link to downstream analyses, and briefly mention the available clustering module.

**Comment by jaclyn-taroni** [comment]
Did not get automagically closed by #101, but should have!
